name: Build & Deploy
on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps: 
      - name: Create SSH directory
        run: mkdir -p ~/.ssh

      - name: Add SSH key to known hosts
        run: |
          echo "${{ secrets.SSH_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts
    
      - name: Deploy NodeJS app
        uses: appleboy/ssh-action@v0.1.2
        with:
          host: ${{secrets.SSH_HOST}}
          key: ${{secrets.SSH_KEY}}
          username: ${{ secrets.SSH_USERNAME }}

          script: |
            cd /var/www/familyFrame
            rm -rf FamilyTree
            git clone git@github.com:AmberRK/FamilyTree.git
            echo 'Deployment successful to digital ocean'
